######################### default configuration ###############################
baseURL = "https://dealicia.com/"
title = "Tienda de repostería en la costa del Sol | d'Alicia • 1 y Caprichos"
theme = "biztrox-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "120"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = "es" # disable language from here
DefaultContentLanguage = "en"

[taxonomies]
  category = "categories"
  tema = "temas"

[related]
threshold = 80.0
includeNewer = true
toLower = false

  [[related.indices]]
  name = "type"
  weight = 1.0

  [[related.indices]]
  name = "category"
  weight = 10.0

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/magnific-popup/magnific-popup.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick-theme.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/animate/animate.css"
  [[params.plugins.css]]
  URL = "https://cdn.snipcart.com/themes/v3.0.17/default/snipcart.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/magnific-popup/magnific-popup.min.js"
  [[params.plugins.js]]
  URL = "plugins/filterizr/jquery.filterizr.min.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/gmap.js"


#################################### navigation ##################################
[menu]

### English ###

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 1

  # footer menu
  [[menu.footer]]
  name = "Legal"
  URL = "#"
  weight = 1

  [[menu.footer]]
  name = "Sitemap"
  URL = "sitemap.xml"
  weight = 2

  [[menu.footer]]
  name = "Privacy Policy"
  URL = "#"
  weight = 3

  [[menu.footer]]
  name = "Terms & Conditions"
  URL = "#"
  weight = 4

########################### default parameters #################################
[params]
logo = "images/logo.png"
logo_white = "images/logo-footer.png"
mail = "hola@dealicia.com"
mobile = "952 92 71 99"
og_image = "images/logo.png"

# Meta data
description = "KH Plumbing • Dunedin's Best Plumbing Service"
author = "normal media"
# contact form
contact_form_action = "#"
# Google Analitycs
google_analitycs_id = "Your ID"

# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# snipcart public api key
snipcartAPI = "MmU3ZTUxYzctMzQwZC00ZDBjLThiZjctMjk3M2VjZDA1ZWQ3NjM3MzMwMTIzMTgzMTYyMDI4"
currency = "€"

# nav Button
[params.nav_button]
enable = false
link = "contact"

# preloader?
[params.preloader]
enable = false
preloader = "images/preloader.gif"

############################ Contact information ############################
[[params.contacts]]
icon = "ti-mobile"

  [[params.contacts.contact]]
  contact_item = "952 88 56 51 - Guadalmina"

  [[params.contacts.contact]]
  contact_item = "952 92 71 99 - El Pilar"

  [[params.contacts.contact]]
  contact_item = "956 79 67 79 - Sotogrande"

[[params.contacts]]
icon = "ti-email"

  [[params.contacts.contact]]
  contact_item = "hola@dealicia.com"
  contact_link = "mailto:hola@dealicia.com"

[[params.contacts]]
icon = "ti-map-alt"
title = "Guadalmina"

  [[params.contacts.contact]]
  contact_item = "C.C. Guadalmina, Edif. 1, Local 4, San Pedro de Alcántara, 29680, Málaga"
  contact_link = "https://www.google.com/maps/place/D%E2%80%99Alicia+Caf%C3%A9+Guadalmina/@36.474186,-5.0062314,17z/data=!3m1!4b1!4m5!3m4!1s0xd732a45d0b35113:0x97fb95c29e578bd4!8m2!3d36.4741817!4d-5.0040374?hl=es-ES"

[[params.contacts]]
icon = "ti-map-alt"
title = "El Pilar"

  [[params.contacts.contact]]
  contact_item = "C.C. El Pilar, Local 9, Urb. El Pilar, KM. 168. Ctra. Nacional 340, Estepona, 29680, Málaga"
  contact_link = "https://www.google.com/maps/place/d'Alicia+Caf%C3%A9+-+El+Pilar+(Estepona)/@36.4666336,-5.0283366,17z/data=!3m1!4b1!4m5!3m4!1s0xd732afb7990a1dd:0x4dca0d013859a719!8m2!3d36.4666293!4d-5.0261426?hl=es-ES"

[[params.contacts]]
icon = "ti-map-alt"
title = "Sotogrande"

  [[params.contacts.contact]]
  contact_item = "C.C. Sotomarket, Local 6, Autopista A7, KM 130. Sotogrande, 11310, Cádiz"
  contact_link = "https://www.google.com/maps/place/d'Alicia+Caf%C3%A9+Sotogrande/@36.2913249,-5.3034452,17z/data=!3m1!4b1!4m5!3m4!1s0xd0cc499f93c3f3b:0xd5dbbe47be949eb0!8m2!3d36.2913206!4d-5.3012512?hl=es-ES"


############################ google map #####################################
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################ client logo slider #############################
[[params.clients_logo_slider]]
logo = "images/client-logo/client-logo-1.png"
link = "#"

[[params.clients_logo_slider]]
logo = "images/client-logo/client-logo-2.png"
link = "https://examplesite.com"

[[params.clients_logo_slider]]
logo = "images/client-logo/client-logo-3.png"
link = "#"

[[params.clients_logo_slider]]
logo = "images/client-logo/client-logo-4.png"
link = "https://examplesite.com"

[[params.clients_logo_slider]]
logo = "images/client-logo/client-logo-5.png"
link = "#"

[[params.clients_logo_slider]]
logo = "images/client-logo/client-logo-3.png"
link = "https://examplesite.com"

########################### social icon #####################################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/dealicia.cafe/"

[[params.social]]
icon = "ti-tumblr-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://t.me/dealicia_cafe"

[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "https://www.instagram.com/dealicia_cafe/"

[[params.social]]
icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
link = "https://www.pinterest.es/dealicia_cafe/"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UCNxq6F5v3u2R06gFaQfmoBg/"

# opening hours
[[params.footer.openingHour]]
day = "Lunes-Sábado"
time = "08.30-14.30"

[[params.footer.openingHour]]
day = "Domingo"
time = "Cerrado"


[Languages]

  ################################### English language #####################################
  [Languages.en]
  languageName = "En"
  languageCode = "en-us"
  contentDir = "content/english"
  weight = 1
  home = "Home"

  # footer
  [Languages.en.params.footer]
  content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt labore dolore magna aliqua enim."

  # copyright
  copyright = "Copyright &copy; 2022 KH Plumbing"
